---
title: "Hotel Booking"
output: html_document
---

```{r, message=FALSE, include=FALSE}
#Include libraries
library(tidyverse)
library(lubridate)
```

```{r}
hotel_data <- read_csv('hotel_bookings.csv')
head(hotel_data)
```

```{r}
#Types of hotel
unique(hotel_data$hotel)

#Percentage of cancellation
mean(hotel_data$is_canceled)

#How early (in days) on average people book 
mean(hotel_data$lead_time)

#Range of dataset.

unique(with(hotel_data, paste(arrival_date_year, arrival_date_month)))
```

```{r}
#plot for specific month
hotel_data %>%
  dplyr::filter(arrival_date_month == 'July', is_canceled == 0) %>%
  group_by(country, hotel) %>%
  summarise(total_people = sum(adults + children + babies)) %>%
  mutate(total = sum(total_people)) %>%
  ungroup %>%
  arrange(desc(total)) %>%
  dplyr::filter(country %in% head(unique(country), 10)) %>%
  ggplot() + aes(reorder(country, -total_people), total_people, fill = hotel) + 
  geom_col(position = 'dodge') + 
  labs(title = "Number of visitors P*",
       x = 'Country', 
       y = 'Count',
       caption = '*Visitors include adults and small childrens of all age') +
  scale_fill_manual(values = c('red', 'blue'), name = 'Type of Hotel') + 
  theme_bw() + 
  theme(legend.position=c(.9,.75))
```


```{r}
hotel_data %>%
  dplyr::filter(is_canceled == 0) %>%
  group_by(hotel) %>%
  summarise(total_visitors = sum(adults + children + babies, na.rm = TRUE)) %>%
  arrange(desc(total_visitors))
```

```{r}
hotel_data %>%
  dplyr::filter(is_canceled == 0) %>%
  group_by(hotel, arrival_date_month) %>%
  summarise(total_visitors = sum(adults + children + babies, na.rm = TRUE)) %>%
  mutate(arrival_date_month = factor(arrival_date_month, month.name)) %>%
  ggplot(aes(arrival_date_month, total_visitors, color = hotel, group = hotel)) + 
  geom_line() + 
   labs(title = "Number of visitors* by month",
       x = 'Month', 
       y = 'Count',
       caption = '*Visitors include adults and small childrens of all age') +
  scale_color_manual(values = c('red', 'blue'), name = 'Type of Hotel') + 
  theme_bw() + 
  theme(legend.position=c(.9,.75))
```

```{r}
#Percentage of people who come with kids. 
mean(hotel_data$children > 0 | hotel_data$babies > 0, na.rm = TRUE) * 100
```

```{r}
#Average length of stay based on number of children
hotel_data %>%
  mutate(total_child = children + babies, 
         total_time = stays_in_weekend_nights + stays_in_week_nights) %>%
  group_by(total_child) %>%
  summarise(average_stay = round(mean(total_time, na.rm = TRUE), 2)) %>%
  na.omit()
```


```{r}
hotel_data %>%
  mutate(total = adults + children + babies) %>%
  group_by(country) %>%
  summarise(total = sum(total, na.rm = TRUE)) %>%
  slice_max(total, n = 6) %>%
  left_join(hotel_data, by = 'country') %>%
  count(country, market_segment) %>%
  ggplot() + aes(market_segment, n) + 
  geom_col() + facet_wrap(~country) + 
  labs(x = 'Market Segment', y = 'Total number of bookings', 
       title = 'Which marketing segment is used by top 5 countries ?') + 
  theme_bw()
```

```{r}
#Include animation
```